// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DownloadableContent: typeof import('./components/DownloadableContent.vue')['default']
    FlipFlopDisplay: typeof import('./components/tools/digital-electronics/flip-flop/FlipFlopDisplay.vue')['default']
    FlipFlopSettingsMenu: typeof import('./components/tools/digital-electronics/flip-flop/FlipFlopSettingsMenu.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    MainNav: typeof import('./components/nav/MainNav.vue')['default']
    MainNavItem: typeof import('./components/nav/MainNavItem.vue')['default']
  }
}

export { }
