// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    MainNav: typeof import('./components/MainNav.vue')['default']
    MainNavItem: typeof import('./components/MainNavItem.vue')['default']
  }
}

export { }
