name: CI

on:
  push:
  pull_request:

jobs:
  base:
    name: Build base image
    uses: ./.github/workflows/docker.yml
    with:
      push: false
      run: false
      target: base
    secrets: inherit

  checks:
    strategy:
      fail-fast: false
      matrix:
        target: [lint, check]
    name: Build ${{ matrix.target }} image
    needs: base
    uses: ./.github/workflows/docker.yml
    with:
      push: false
      run: true
      target: ${{ matrix.target }}
    secrets: inherit

  unit:
    name: Test and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 19.x
          registry-url: https://registry.npmjs.org/

      - name: Test
        run: pnpm run test:unit:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: unit
          files: ./coverage/coverage-final.json

  publish:
    name: Build and push final image
    needs: [ base, checks, unit]
    uses: ./.github/workflows/docker.yml
    with:
      push: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/dependabot/') }}
      run: false
      target: final
    secrets: inherit
