name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  installDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

  lint:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Lint code
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: pnpm run build

  unit:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Test
        run: pnpm run test:unit:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          files: ./coverage/coverage-final.json

  e2e:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Setup playwright
        run: pnpm run playwright:install

      - name: Test
        run: pnpm run test:e2e
