name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  base:
    name: Build base image
    uses: ./.github/workflows/docker.yml
    with:
      push: false
      target: base
      tags: withoutaname/withoutaname.eu:base
    secrets: inherit

  checks:
    strategy:
      matrix:
        target: [lint, check, e2etest, build]
    name: Build ${{ matrix.target }} image
    needs: base
    uses: ./.github/workflows/docker.yml
    with:
      push: false
      target: ${{ matrix.target }}
      tags: withoutaname/withoutaname.eu:${{ matrix.target }}
    secrets: inherit

  unit:
    name: Test and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun run test:unit:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          files: ./coverage/coverage-final.json

  version:
    name: Get current version
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current version
        id: version
        run: |
          TAGS=withoutaname/withoutaname.eu:latest
          VERSION=$(expr match "$(git tag --points-at HEAD)" '.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\).*') \
          && TAGS="$TAGS,withoutaname/withoutaname.eu:$VERSION" \
          || echo "No version found"
          echo "::set-output name=value::$TAGS"

  publish:
    name: Build and push final image
    needs: [ base, checks, unit, version]
    if: ${{ success() && github.event_name == 'push' && github.ref_name == 'master' }}
    uses: ./.github/workflows/docker.yml
    with:
      push: true
      target: final
      tags: ${{ needs.version.outputs.value }}
    secrets: inherit
