name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-latest
          restore-keys: |
            pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Check code formatting with prettier
        run: pnpm exec prettier --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ matrix.node-version }}
          restore-keys: |
            pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
          run_install: true

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      #      - name: Test
      #        run: pnpm run test

      - name: Build
        run: pnpm run build
  #      - name: Upload coverage to Codecov
  #        uses: codecov/codecov-action@v2
  #        with:
  #          flags: unittests

  deploy:
    runs-on: ubuntu-latest
    needs: [build, prettier]
    if: ${{ success() && github.event_name == 'push' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-latest
          restore-keys: |
            pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: pnpm run build

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /var/www/withoutaname/
