name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  installDependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

  prettier:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Check code formatting with prettier
        run: pnpm exec prettier --check .

  build:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: pnpm run build

  unit:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Test
        run: pnpm run test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unit
          files: ./coverage/coverage-final.json

  e2e:
    runs-on: ubuntu-latest
    needs: installDependencies
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Test
        run: pnpm run cy:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: e2e
          files: ./coverage/coverage-final.json

  deploy:
    runs-on: ubuntu-latest
    needs: [build, prettier, unit, e2e]
    if: ${{ success() && github.event_name == 'push' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: pnpm run build

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /var/www/withoutaname/
