name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTB_SERVER }}
        username: ${{ secrets.FTB_USER }}
        password: ${{ secrets.FTB_PASSWORD }}
        protocol: ftps
        local-dir: ./dist/
        server-dir: /var/www/withoutaname/
