name: Build docker image

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      run:
        required: true
        type: boolean
      target:
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: false

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            withoutaname/withoutaname.eu
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
            type=raw,value=current,enable=${{ ! inputs.push }}
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ github.event_name == 'push' }}

      - name: Login to Docker Hub
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          username: withoutaname
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          target: ${{ inputs.target }}
          load: ${{ inputs.run }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run
        if: ${{ inputs.run }}
        run: docker run --rm withoutaname/withoutaname.eu:current
