name: Build docker image

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      target:
        required: true
        type: string
      tags:
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: withoutaname
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          target: ${{ inputs.target }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          cache-from: type=registry,ref=withoutaname/withoutaname.eu:buildcache
          cache-to: type=registry,ref=withoutaname/withoutaname.eu:buildcache,mode=max
